name: Gerar Release Automática

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: 1. Checkout do Código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necessário para ler tags

    - name: 2. Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. Compilar App (Release)
      # Restauramos e compilamos tudo do zero
      run: dotnet build LatexStudio.csproj -c Release

    - name: 4. Gerar MSI via WiX
      run: |
        # Usamos as ferramentas WiX que já estão no Windows do GitHub
        heat dir bin/Release/net8.0-windows -dr INSTALLFOLDER -ke -srd -cg ProductComponents -var var.SourceDir -gg -out components.wxs
        candle -dSourceDir=bin/Release/net8.0-windows Product.wxs components.wxs
        light -out LatexStudio_Setup.msi Product.wixobj components.wixobj

    - name: 5. Sincronizar Tag no Repositório Público
      # Este passo garante que a tag v1.x.x existe lá, evitando o erro 400
      run: |
        git remote add public https://${{ secrets.RELEASE_TOKEN }}@github.com/munanyo30/LatexStudio-Releases.git
        git push public ${{ github.ref_name }}

    - name: 6. Criar Release no Repositório Público
      uses: softprops/action-gh-release@v2
      with:
        repository: munanyo30/LatexStudio-Releases
        token: ${{ secrets.RELEASE_TOKEN }}
        name: Latex Studio ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: LatexStudio_Setup.msi
        generate_release_notes: true
        make_latest: true
