name: Gerar Release Automática

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Permite criar releases e fazer upload de ficheiros
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Resolve o aviso de depreciação do Node 20

    steps:
    - name: 1. Checkout do Código
      uses: actions/checkout@v4

    - name: 2. Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. Restaurar Dependências
      run: dotnet restore LatexStudio.sln

    - name: 4. Compilar App (Release)
      run: dotnet build LatexStudio.csproj -c Release --no-restore

    - name: 5. Gerar Instalador (Inno Setup)
      run: iscc LatexStudio.iss

    - name: 6. Criar Release no Repositório Público
      uses: softprops/action-gh-release@v2
      with:
        repository: munanyo30/LatexStudio-Releases # Repositório Público
        token: ${{ secrets.RELEASE_TOKEN }}      # Token com permissão de escrita no outro repo
        name: Latex Studio ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: Output/LatexStudio_Setup.exe
        generate_release_notes: true
